steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--target=base",
        "-t",
        "gcr.io/nathanriver-test/inspire-client:dev",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/nathanriver-test/inspire-client:dev"]
