steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--target=production",
        "-t",
        "gcr.io/nathanriver-test/inspire-client:$SHORT_SHA",
        "client",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/nathanriver-test/inspire-client:$SHORT_SHA"]
